# Generated by Django 5.1.4 on 2025-01-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
